# Exercises

>![info](../images/info.svg) Try to solve exercises in every chapter using only the features discussed until that chapter. Some of the exercises will be easier to solve with techniques presented in later chapters, but the aim of these exercises is to explore the features presented so far.

>![info](../images/info.svg) For solutions, see [Exercise_solutions.md](https://github.com/learnbyexample/py_regular_expressions/blob/master/exercises/Exercise_solutions.md).

<br>

In [1]:
import re

# re introduction

**a)** Check whether the given strings contain `0xB0`. Display a boolean result as shown b

In [2]:
line1 = 'start address: 0xA0, func1 address: 0xC0'
line2 = 'end address: 0xFF, func2 address: 0xB0'

In [3]:
bool(re.search(r'0xB0', line1))     ##### add your solution here


False

In [4]:
bool(re.search(r'0xB0', line2))     ##### add your solution here

True

**b)** Replace all occurrences of `5` with `five` for the given string.

In [5]:
ip = 'They ate 5 apples and 5 oranges'
re.sub(r'5','five',ip)  

'They ate five apples and five oranges'

**c)** Replace first occurrence of `5` with `five` for the given string.

In [6]:
ip = 'They ate 5 apples and 5 oranges'
re.sub('5','five', ip, count=1)       ##### add your solution here

'They ate five apples and 5 oranges'

**d)** For the given list, filter all elements that do `*not*` contain `e`.

In [7]:
items = ['goal', 'new', 'user', 'sit', 'eat', 'dinner']

In [8]:
[w for w in items if not re.search(r'e',w)]

['goal', 'sit']

**e)** Replace all occurrences of `note` irrespective of case with `X`.

In [9]:
ip = 'This note should not be NoTeD'

In [10]:
re.sub(r'[Nn]o[Tt]e', "X", ip)

'This X should not be XD'

In [11]:
re.sub(r'note|NoTe', "X", ip)

'This X should not be XD'

In [12]:
re.sub(r'note', 'X',ip,flags = re.I)

'This X should not be XD'

**f)** Check if `at` is present in the given byte input data.

In [13]:
ip = b'tiger imp goat'
bool(re.search(rb'at',ip))

True

**g)** For the given input string, display all lines not containing `start` irrespective of case.

In [14]:
para = '''good start
Start working on that
project you always wanted
stars are shining brightly
hi there
start and try to
finish the book
bye'''

In [15]:
pat = re.compile(r'Start|start', re.I)      ##### add your solution here
>>> for line in para.split('\n'):
...     if not pat.search(line):
...         print(line)

project you always wanted
stars are shining brightly
hi there
finish the book
bye


In [16]:
pat = re.compile(r'start', flags =re.I)      ##### add your solution here
>>> for line in para.split('\n'):
...     if not pat.search(line):
...         print(line)

project you always wanted
stars are shining brightly
hi there
finish the book
bye


**h)** For the given list, filter all elements that contains either `a` or `w`.

In [17]:
items = ['goal', 'new', 'user', 'sit', 'eat', 'dinner']

In [18]:
[w for w in items if re.search(r'a',w) or re.search(r'w',w)]

['goal', 'new', 'eat']

**i)** For the given list, filter all elements that contains both `e` and `n`.

In [19]:
items = ['goal', 'new', 'user', 'sit', 'eat', 'dinner']

In [20]:
[w for w in items if re.search(r'e',w) and re.search(r'n',w)]

['new', 'dinner']

**j)** For the given string, replace `0xA0` with `0x7F` and `0xC0` with `0x1F`.

In [21]:
ip = 'start address: 0xA0, func1 address: 0xC0'
re.sub(r'\.+(0xA0)\.+(0xC0)',r'\.+\0x7F\.+\0x1F',ip)

'start address: 0xA0, func1 address: 0xC0'

In [22]:
ip = 'start address: 0xA0, func1 address: 0xC0'
re.sub(r'0xC0', '0x1F', re.sub(r'0xA0', '0x7F', ip))

'start address: 0x7F, func1 address: 0x1F'

In [23]:
ip = 'start address: 0xA0, func1 address: 0xC0'
lst1 = ['0xA0','0xC0']
lst2 = ['0x7F','0x1F' ]
for i in range(2):
    x =re.sub(lst1[i],lst2[i], ip )
    ip = x

print(x)

start address: 0x7F, func1 address: 0x1F


# Anchors

**a)** Check if the given strings start with `be`.

In [24]:
line1 = 'be nice'
line2 = '"best!"'
line3 = 'better?'
line4 = 'oh no\nbear spotted'


In [25]:
pat = re.compile("^be")      ##### add your solution here

In [26]:
bool(pat.search(line1))

True

In [27]:
bool(pat.search(line2))

False

In [28]:
bool(pat.search(line3))

True

In [29]:
bool(pat.search(line4))

False

**b)** For the given input string, change only whole word `red` to `brown`

## `\b` 
word boundry

In [30]:
words = 'bred red spread credible'

In [31]:
re.sub(r'\bred\b', 'brown',words)     ##### add your solution here
# \b Anchors a match to a word boundary.
# it can create boundry that mean restricted

'bred brown spread credible'

**c)** For the given input list, filter all elements that contains `42` surrounded by word characters.


## `\B` 
reverse word boundry

In [32]:
words = ['hi42bye', 'nice1423', 'bad42', 'cool_42a', 'fake4b']

In [33]:
[w for w in words if re.search('\w+42\w+',w)]

['hi42bye', 'nice1423', 'cool_42a']

In [34]:
[w for w in words if re.search('\B42\B',w)]

['hi42bye', 'nice1423', 'cool_42a']

 1 **d)** For the given input list, filter all elements that start with `den` or end with `ly`.

In [35]:
items = ['lovely', '1\ndentist', '2 lonely', 'eden', 'fly\n', 'dent']

In [36]:
[e for e in items if re.search(r'^(den)|(ly)$',e)]

['lovely', '2 lonely', 'fly\n', 'dent']

## `\A` 
Anchor a match to the start of `<string>`

## or

In [37]:
[e for e in items if re.search(r'^(den)',e) or re.search(r'(ly)$',e)]

['lovely', '2 lonely', 'fly\n', 'dent']

In [38]:
[e for e in items if re.search(r'\Aden', e) or re.search(r'ly\Z', e)]

['lovely', '2 lonely', 'dent']

**e)** For the given input string, change whole word `mall` to `1234` only if it is at the start of a line.

In [39]:
para = '''\
ball fall wall tall
mall call ball pall
wall mall ball fall
mallet wallet malls'''

In [40]:
print(re.sub('(mall)', '1234', para, count =1))

ball fall wall tall
1234 call ball pall
wall mall ball fall
mallet wallet malls


flags

In [41]:
print(re.sub(r'^mall\b', '1234', para, flags= re.M))

ball fall wall tall
1234 call ball pall
wall mall ball fall
mallet wallet malls


**f)** For the given list, filter all elements having a line starting with `den` or ending with `ly`.


In [42]:
items = ['lovely', '1\ndentist', '2 lonely', 'eden', 'fly\nfar', 'dent']

In [43]:
[w for w in items if re.search("^(den)|(ly)$", w, re.M)]

['lovely', '1\ndentist', '2 lonely', 'fly\nfar', 'dent']

In [44]:
[e for e in items if re.search(r'^den', e, flags=re.M) or re.search(r'ly$', e, flags=re.M)]

['lovely', '1\ndentist', '2 lonely', 'fly\nfar', 'dent']

**g)** For the given input list, filter all whole elements `12\nthree` irrespective of case.

In [45]:
items = ['12\nthree\n', '12\nThree', '12\nthree\n4', '12\nthree']

## flags=re.M
## re.serach 
(wrong)

In [46]:
[w for w in items if re.search("12\nthree", w, flags=re.M)]

['12\nthree\n', '12\nthree\n4', '12\nthree']

In [47]:
[w for w in items if re.search("^[1].+e", w, re.M)]

[]

## flags= re.I
## re.fullmatch()
(right)

In [48]:
[e for e in items if re.fullmatch(r'12\nthree', e, flags=re.I)]

['12\nThree', '12\nthree']

 **h)** For the given input list, replace `hand` with `X` for all elements that start with `hand` followed by at least one word character.

In [49]:
items = ['handed', 'hand', 'handy', 'unhanded', 'handle', 'hand-2']

In [50]:
[re.sub('^[h].+d\B','X',w) for w in items]

['Xed', 'hand', 'Xy', 'unhanded', 'Xle', 'hand-2']

## \b with \B

In [51]:
[re.sub(r'\bhand\B','X', w) for w in items]

['Xed', 'hand', 'Xy', 'unhanded', 'Xle', 'hand-2']

**i)** For the given input list, filter all elements starting with `h`. Additionally, replace `e` with `X` for these filtered elements.

In [52]:
items = ['handed', 'hand', 'handy', 'unhanded', 'handle', 'hand-2']

In [53]:
[re.sub('(?<=^(hand))|(?<=^(handl))(e)','X',w) for w in items if re.search(r'\Ah', w) ]

['handXed', 'handX', 'handXy', 'handXlX', 'handX-2']

## \A
Start match anchor

In [54]:
[re.sub(r'e', 'X', w) for w in items if re.search(r'\Ah', w)]

['handXd', 'hand', 'handy', 'handlX', 'hand-2']

# Alternation and Grouping


**a)** For the given input list, filter all elements that start with `den` or end with `ly`

In [55]:
items = ['lovely', '1\ndentist', '2 lonely', 'eden', 'fly\n', 'dent']

## |
Specifies a set of alternatives on which to match.

In [56]:
lst = []
for w in items:
    if re.search('den\w+|\w+ly',w):
        lst.append(w)
        

In [57]:
lst

['lovely', '1\ndentist', '2 lonely', 'fly\n', 'dent']

## \Z \z
\Z  matches just before a `single newline` at the end of the search string

In [58]:
[e for e in items if re.search(r'\Aden|ly\Z', e)]
# (correct)

['lovely', '2 lonely', 'dent']

In [59]:
[e for e in items if re.search(r'^den\w+|\w+ly$',e)]

['lovely', '2 lonely', 'fly\n', 'dent']

**b)** For the given list, filter all elements having a line starting with `den` or ending with `ly`.

In [60]:
items = ['lovely', '1\ndentist', '2 lonely', 'eden', 'fly\nfar', 'dent']

In [61]:
[e for e in items if re.search(r'^den|ly$',e)]

['lovely', '2 lonely', 'dent']

## flags = re.M

In [62]:
[e for e in items if re.search(r'^den|ly$',e, flags = re.M)]

['lovely', '1\ndentist', '2 lonely', 'fly\nfar', 'dent']

**c)** For the given input strings, replace all occurrences of `removed` or `reed` or `received` or `refused` with `X`.


In [63]:
s1 = 'creed refuse removed read'
s2 = 'refused reed redo received'

In [64]:
pat = re.compile('reed|received|refused|removed')
print(pat.sub('X', s1))
print(pat.sub('X', s2))

cX refuse X read
X X redo X


## |
multiple options

In [65]:
pat = re.compile('re(|ceiv|fus|mov)ed')

In [66]:
pat.sub('X', s1)

'cX refuse X read'

In [67]:
pat.sub('X', s1)

'cX refuse X read'

**d)** For the given input strings, replace all matches from the list `words` with `A`.


In [68]:
s1 = 'plate full of slate'
s2 = "slated for later, don't be late"
words = ['late', 'later', 'slated']

In [69]:
pat = re.compile("|".join(words))
print(pat.sub('A', s1))
print(pat.sub('A', s2))

pA full of sA
A for Ar, don't be A


**e)** Filter all whole elements from the input list `items` based on elements listed in `words`.

In [70]:
items = ['slate', 'later', 'plate', 'late', 'slates', 'slated ']
words = ['late', 'later', 'slated']

# .fullmatch

In [71]:
pat = re.compile("|".join(words))

[w for w in items if pat.fullmatch(w)]

['later', 'late']

# Escaping metacharacters
`\*, \+,\^,\\, \|`

**a)** Transform the given input strings to the expected output using same logic on both strings.

In [72]:
str1 = '(9-2)*5+qty/3'

str2 = '(qty+4)/2-(9-2)*5+pq/4'


In [73]:
re.sub(r'\(9\-2\)\*5', '35', str1)

'35+qty/3'

In [74]:
re.sub(r'\(qty\+4\)\/2\-\(9\-2\)\*5','(qty+4)/2-35', str2)

'(qty+4)/2-35+pq/4'

**b)** Replace `(4)\|` with `2` only at the start or end of given input strings.

In [75]:
s1 = r'2.3/(4)\|6 foo 5.3-(4)\|'

s2 = r'(4)\|42 - (4)\|3'

s3 = 'two - (4)\\|\n'


In [76]:
# raw string need 

In [77]:
pat = re.compile(r'\A\(4\)\\\||\(4\)\\\|\Z')
# \(4\)\\\ ==(4)\|

In [78]:
pat.sub('2',s1)

'2.3/(4)\\|6 foo 5.3-2'

In [79]:
pat.sub('2',s2)

'242 - (4)\\|3'

In [80]:
pat.sub('2',s3)

'two - (4)\\|\n'

**c)** Replace any matching element from the list `items` with `X` for given the input strings. Match the elements from `items` literally. Assume no two elements of `items` will result in any matching conflict.


In [81]:
items = ['a.b', '3+n', r'x\y\z', 'qty||price', '{n}']


## re.escape() 
### same as re.match()
lot of special characters that you want the parser to take literally instead of as metacharacters

In [82]:
pat = re.compile("|".join(re.escape(e) for e in items))      ##### add your solution here

In [83]:
pat.sub('X','0a.bcd')

'0Xcd'

In [84]:
pat.sub('X', 'E{n}AMPLE')

'EXAMPLE'

In [85]:
pat.sub('X', r'43+n2 ax\y\ze')

'4X2 aXe'

**d)** Replace backspace character `\b` with a single space character for the given input string.

# \b = \x08

In [86]:
ip = '123\b456'
ip

'123\x08456'

In [87]:
re.sub(r'\x08',' ',ip)

'123 456'

Raw string

In [88]:
ip = r'123\b456'
ip

'123\\b456'

In [89]:
re.sub(r'\\b',' ',ip)

'123 456'

**e)** Replace all occurrences of `\e` with `e`.

In [90]:
ip = r'th\er\e ar\e common asp\ects among th\e alt\ernations'
ip

'th\\er\\e ar\\e common asp\\ects among th\\e alt\\ernations'

In [91]:
re.sub(r'\\e', 'e',ip)

'there are common aspects among the alternations'

**f)** Replace any matching item from the list `eqns` with `X` for given the string `ip`. Match the items from `eqns` literally.

In [92]:
ip = '3-(a^b)+2*(a^b)-(a/b)+3'
eqns = ['(a^b)', '(a/b)', '(a^b)+2']


In [93]:
ip

'3-(a^b)+2*(a^b)-(a/b)+3'

In [94]:
a = "|".join(eqns)
print(a)

(a^b)|(a/b)|(a^b)+2


In [95]:
print('copy{}'.format(a))

copy(a^b)|(a/b)|(a^b)+2


In [96]:
re.compile("|".join(re.escape(e) for e in eqns))

re.compile(r'\(a\^b\)|\(a/b\)|\(a\^b\)\+2', re.UNICODE)

In [97]:
pat.sub('X', ip)

'3-(a^b)+2*(a^b)-(a/b)+3'

### soreted(,key = len, reverse = True)

In [98]:
eqns_sorted = sorted(eqns, key=len, reverse=True)
pat = re.compile('|'.join(re.escape(s) for s in eqns_sorted))

In [99]:
pat.sub('X', ip)

'3-X*X-X+3'

# Dot metacharacter and Quantifiers

Since `.` metacharacter doesn't match newline character by default, assume that the input strings in the following exercises will not contain newline characters.


**a)** Replace `42//5` or `42/5` with `8` for the given input.

In [100]:
ip = 'a+42//5-c pressure*3+42/5-14256'

In [101]:
re.sub(r'42(\/\/|\/)5','8',ip)

'a+8-c pressure*3+8-14256'

**b)** For the list `items`, filter all elements starting with `hand` and ending with at most one more character or `le`.


In [102]:
items = ['handed', 'hand', 'handled', 'handy', 'unhand', 'hands', 'handle']

In [103]:
[w for w in items if re.search(r'^(hand)',w) or re.search(r'le$',w)] 

['handed', 'hand', 'handled', 'handy', 'hands', 'handle']

# `?` 
Matches zero or one repetitions of the preceding regex

# `dot (.)`

dot(.)Specifies a wildcard.

In [104]:
[w for w in items if re.fullmatch(r'^hand(.|le)?',w)] 

['hand', 'handy', 'hands', 'handle']

**c)** Use `re.split` to get the output as shown for the given input strings.

In [105]:
>>> eqn1 = 'a+42//5-c'
>>> eqn2 = 'pressure*3+42/5-14256'
>>> eqn3 = 'r*42-5/3+42///5-42/53+a'

# re.split

In [106]:
re.split('42//5',eqn1)

['a+', '-c']

In [107]:
re.split('42/5',eqn2)

['pressure*3+', '-14256']

In [108]:
re.split('42/5',eqn3)

['r*42-5/3+42///5-', '3+a']

## ?
Matches zero or one repetitions of the preceding regex

In [109]:
pat = re.compile(r'42//?5')

In [110]:
pat.split(eqn1)

['a+', '-c']

In [111]:
pat.split(eqn2)

['pressure*3+', '-14256']

In [112]:
pat.split(eqn3)

['r*42-5/3+42///5-', '3+a']

# `*`
zero or more repetitions

In [113]:
pat = re.compile(r'42//?5')


In [114]:
pat.split(eqn1)

['a+', '-c']

In [115]:
pat.split(eqn2)

['pressure*3+', '-14256']

In [116]:
pat.split(eqn3)

['r*42-5/3+42///5-', '3+a']

**d)** For the given input strings, remove everything from the first occurrence of `i` till end of the string.

In [117]:
s1 = 'remove the special meaning of such constructs'
s2 = 'characters while constructing'

# `+ `
at least one or more repetitions
# `.`
The `.` metacharacter matches any `single character` `except a newline`:

In [118]:
pat = re.compile(r'i.+')

In [119]:
pat.sub('',s1)

'remove the spec'

In [120]:
pat.sub('',s2)

'characters wh'

# `*`
zero or more repetitions

**e)** For the given strings, construct a RE to get output as shown.

In [121]:
str1 = 'a+b(addition)'
str2 = 'a/b(division) + c%d(#modulo)'
str3 = 'Hi there(greeting). Nice day(a(b)'

In [122]:
remove_parentheses = re.compile(r'\(.*\)')

## `.*?`
`(.*?)` matches any character `(.)` any number of times `(*)`, as few times as possible to make the regex match `(?)

In [123]:
remove_parentheses = re.compile(r'\(.*?\)')

In [124]:
remove_parentheses.sub('', str1)

'a+b'

In [125]:
remove_parentheses.sub('', str2)

'a/b + c%d'

In [126]:
remove_parentheses.sub('', str3)

'Hi there. Nice day'

**f)** Correct the given RE to get the expected output.

In [127]:
words = 'plink incoming tint winter in caution sentient'
change = re.compile(r'int|in|ion|ing|inco|inter|ink')

In [128]:
# wrong output
change.sub('X', words)

'plXk XcomXg tX wXer X cautX sentient'

In [129]:
# expected output
# 'plX XmX tX wX X cautX sentient'

change = re.compile(r'in(g|co|ter|k|t)?|ion')       ##### add your solution here

In [130]:
change.sub('X', words)

'plX XmX tX wX X cautX sentient'

**g)** For the given greedy quantifiers, what would be the equivalent form using `{m,n}` representation?

* `?` is same as
`m=0 , n= 1`
* `*` is same as
`m=0 , n = `$\infty$
* `+` is same as
`m=1 , n=` $\infty$

**h)** `(a*|b*)` is same as `(a|b)*` — True or False?
<br>False
* `(a*|b*)` this will match only one repetation i.e aa or bbbb
* `(a|b)*` this will match combination of both i.e ab , aabb, abb 

**i)** For the given input strings, remove everything from the first occurrence of `test` (irrespective of case) till end of the string, provided `test` isn't at the end of the string.


In [131]:
s1 = 'this is a Test'
s2 = 'always test your RE for corner cases'
s3 = 'a TEST of skill tests?'


In [132]:
pat = re.compile(r'test.*',flags = re.I)      ##### add your solution here

print(pat.sub('', s1))
print(pat.sub('', s2))
print(pat.sub('', s3))

this is a 
always 
a 


In [133]:
pat = re.compile(r'(test|TEST).*',)      ##### add your solution here

print(pat.sub('', s1))
print(pat.sub('', s2))
print(pat.sub('', s3))

this is a Test
always 
a 


In [134]:
pat = re.compile('test.+', flags=re.I)     ##### add your solution here

print(pat.sub('', s1))
print(pat.sub('', s2))
print(pat.sub('', s3))

this is a Test
always 
a 


**j)** For the input list `words`, filter all elements starting with `s` and containing `e` and `t` in any order.

In [135]:
words = ['sequoia', 'subtle', 'exhibit', 'asset', 'sets', 'tests', 'site']

In [136]:
pat = re.compile('\As.*(e.*t|t.*e).*')

In [137]:
[w for w in words if pat.search(w)]

['subtle', 'sets', 'site']

**k)** For the input list `words`, remove all elements having less than `6` characters.

In [138]:
words = ['sequoia', 'subtle', 'exhibit', 'asset', 'sets', 'tests', 'site']

In [139]:
[w for w in words if re.search(r'.{6}',w)]

['sequoia', 'subtle', 'exhibit']

In [140]:
[w for w in words if re.search(r'.{6,}', w)]

['sequoia', 'subtle', 'exhibit']

**l)** For the input list `words`, filter all elements starting with `s` or `t` and having a maximum of `6` characters.

In [141]:
words = ['sequoia', 'subtle', 'exhibit', 'asset', 'sets', 'tests', 'site']

In [142]:
[w for w in words if re.search(r'.{,5}', w) and re.search(r'.*(s*|t*).*', w)]

['sequoia', 'subtle', 'exhibit', 'asset', 'sets', 'tests', 'site']

In [143]:
[w for w in words if re.fullmatch(r'(s|t).{,5}', w)]
# (correct)

['subtle', 'sets', 'tests', 'site']


**m)** Can you reason out why this code results in the output shown? The aim was to remove all `<characters>` patterns but not the `<>` ones. The expected result was `'a 1<> b 2<> c'`.

In [144]:
ip = 'a<apple> 1<> b<bye> 2<> c<cat>'

In [145]:
re.sub(r'<.+?>', '', ip)

'a 1 2'

.+ means detect any character one or more times 


**n)** Use `re.split` to get the output as shown below for given input strings.

In [146]:
s1 = 'go there  //   "this // that"'
s2 = 'a//b // c//d e//f // 4//5'
s3 = '42// hi//bye//see // carefully'

In [147]:
pat = re.compile(r'\s{1,2}//\s{1,2}')     ##### add your solution here
# (correct)

In [148]:
pat.split(s1)

['go there', ' "this', 'that"']

In [149]:
pat.split(s2)

['a//b', 'c//d e//f', '4//5']

In [150]:
pat.split(s3)

['42// hi//bye//see', 'carefully']

In [151]:
pat = re.compile(r'\s+//\s+')     ##### add your solution here

In [152]:
pat.split(s1)

['go there', '"this', 'that"']

In [153]:
pat.split(s2)

['a//b', 'c//d e//f', '4//5']

In [154]:
pat.split(s2)

['a//b', 'c//d e//f', '4//5']

In [155]:
pat = re.compile(r' +// +')

In [156]:
pat.split(s1)

['go there', '"this', 'that"']

In [157]:
pat.split(s2)

['a//b', 'c//d e//f', '4//5']

In [158]:
pat.split(s3)

['42// hi//bye//see', 'carefully']

# Working with matched portions

**a)** For the given strings, extract the matching portion from first `is` to last `t`.

first match to last match 

In [159]:
str1 = 'This the biggest fruit you have seen?'
str2 = 'Your mission is to read and practice consistently'

In [160]:
pat = re.compile('(is).*t')

In [161]:
pat.search(str1)

<re.Match object; span=(2, 22), match='is the biggest fruit'>

In [162]:
pat.search(str2)

<re.Match object; span=(6, 47), match='ission is to read and practice consistent'>

**b)** Find the starting index of first occurrence of `is` or `the` or `was` or `to` for the given input strings.


In [163]:
s1 = 'match after the last newline character'
s2 = 'and then you want to test'
s3 = 'this is good bye then'
s4 = 'who was there to see?'

In [165]:
pat = re.compile(r'(is|the|was|to)')

In [166]:
pat.search(s1).start()

12

In [167]:
pat.search(s2).start()

4

In [168]:
pat.search(s3).start()

2

In [169]:
pat.search(s4).start()

4

**c)** Find the starting index of last occurrence of `is` or `the` or `was` or `to` for the given input strings.

In [170]:
s1 = 'match after the last newline character'
s2 = 'and then you want to test'
s3 = 'this is good bye then'
s4 = 'who was there to see?'

In [171]:
pat = re.compile(r'(is|the|was|to)') 

In [172]:
pat.search(s1).end()

15

In [173]:
pat.search(s2).end()

7

In [174]:
pat.search(s3).end()

4

In [175]:
pat.search(s4).end()

7

**d)** The given input string contains `:` exactly once. Extract all characters after the `:` as output.

In [176]:
ip = 'fruits:apple, mango, guava, blueberry'

In [177]:
print(re.search(r':a(.*)', ip))

<re.Match object; span=(6, 37), match=':apple, mango, guava, blueberry'>


In [178]:
re.search(r':a(.*)', ip)[0]


':apple, mango, guava, blueberry'

In [179]:
re.search(r':a(.*)', ip)[1]
# this will capture only match which is in parentheses 

'pple, mango, guava, blueberry'

**e)** The given input strings contains some text followed by `-` followed by a number. Replace that number with its `log` value using `math.log()`.


In [180]:
s1 = 'first-3.14'
s2 = 'next-123'

In [181]:
import math

In [182]:

pat = re.compile('(\d+.\d+)|(\d+)')

In [183]:
s1_log = math.log(float(pat.search(s1)[0]))

In [184]:
s2_log = math.log(int(pat.search(s2)[0]))

In [185]:
pat.sub(str(s1_log),s1)

'first-1.144222799920162'

In [186]:
pat.sub(str(s2_log),s2)

'next-4.812184355372417'

**f)** Replace all occurrences of `par` with `spar`, `spare` with `spare` and `park` with `garden` for the given input strings.

In [187]:
str1 = 'apartment has a park'
str2 = 'do you have a spare cable'
str3 = 'write a parser'

In [188]:
re.sub(r'par','spar',str1)

'aspartment has a spark'

In [189]:
re.sub(r'spare','spare',str2)

'do you have a spare cable'

In [190]:
re.sub(r'park','garden',str2)

'do you have a spare cable'

**g)** Extract all words between `(` and `)` from the given input string as a list. Assume that the input will not contain any broken parentheses.


In [191]:
ip = 'another (way) to reuse (portion) matched (by) capture groups'

In [192]:
re.findall('\(*(\w+)\)',ip)

['way', 'portion', 'by']

**h)** Extract all occurrences of `<` up to next occurrence of `>`, provided there is at least one character in between `<` and `>`.


In [199]:
ip = 'a<apple> 1<> b<bye> 2<> c<cat>'

In [204]:
re.findall(r'<\w+?>',ip)

['<apple>', '<bye>', '<cat>']

In [203]:
re.findall(r'<.+?>',ip)

['<apple>', '<> b<bye>', '<> c<cat>']

**i)** Use `re.findall` to get the output as shown below for the given input strings. Note the characters used in the input strings carefully.


In [196]:
row1 = '-2,5 4,+3 +42,-53 4356246,-357532354 '
row2 = '1.32,-3.14 634,5.63 63.3e3,9907809345343.235 '

In [214]:
pat = re.compile(r'(.+?),(.+?)\s')
# created two groups by the bracess 
#1st group can contain character up to quama(,) 
#2nd group can contain character next to quama(,)
#and this group ends up to next space 

In [215]:
pat.findall(row1)

[('-2', '5'), ('4', '+3'), ('+42', '-53'), ('4356246', '-357532354')]

In [216]:
pat.findall(row2)

[('1.32', '-3.14'), ('634', '5.63'), ('63.3e3', '9907809345343.235')]

**j)** This is an extension to previous question.

* For `row1`, find the sum of integers of each tuple element. For example, sum of `-2` and `5` is `3`.
* For `row2`, find the sum of floating-point numbers of each tuple element. For example, sum of `1.32` and `-3.14` is `-1.82`.

In [266]:
row1 = '-2,5 4,+3 +42,-53 4356246,-357532354 '
row2 = '1.32,-3.14 634,5.63 63.3e3,9907809345343.235 '

In [267]:
pat = re.compile(r'(.+?),(.+?)\x20')

In [268]:
row1 = pat.findall(row1)
row2 = pat.findall(row2)

In [269]:
row2

[('1.32', '-3.14'), ('634', '5.63'), ('63.3e3', '9907809345343.235')]

In [270]:
[(int(i[0])+int(i[1])) for i in row1]

[3, 7, -11, -353176108]

In [271]:
[(float(i[0])+float(i[1])) for i in row2]


[-1.82, 639.63, 9907809408643.234]

**k)** Use `re.split` to get the output as shown below.

In [272]:
ip = '42:no-output;1000:car-truck;SQEX49801'

In [273]:
re.split(r'[;:-]',ip)

['42', 'no', 'output', '1000', 'car', 'truck', 'SQEX49801']

**l)** For the given list of strings, change the elements into a tuple of original element and number of times `t` occurs in that element.

In [274]:
words = ['sequoia', 'attest', 'tattletale', 'asset']

In [281]:
[re.subn(r't', 't', w) for w in words]
# 't' replaced with 't' and also shown how many time it been replace

[('sequoia', 0), ('attest', 3), ('tattletale', 4), ('asset', 1)]

**m)** The given input string has fields separated by `:`. Each field contains four uppercase alphabets followed optionally by two digits. Ignore the last field, which is empty. See [docs.python: Match.groups](https://docs.python.org/3/library/re.html#re.Match.groups) and use `re.finditer` to get the output as shown below. If the optional digits aren't present, show `'NA'` instead of `None`.

In [282]:
ip = 'TWXA42:JWPA:NTED01:'

In [288]:
re.split(r'[:]',ip)

['TWXA42', 'JWPA', 'NTED01', '']

In [303]:
for i in re.finditer(r'(.{4})(..)?:',ip):
    print(i.groups(default='NA'))

('TWXA', '42')
('JWPA', 'NA')
('NTED', '01')


**Note** that this is different from `re.findall` which will just give empty string instead of `None` when a capture group doesn't participate.


**n)** Convert the comma separated strings to corresponding `dict` objects as shown below.

In [330]:
row1 = 'name:rohan,maths:75,phy:89,'
row2 = 'name:rose,maths:88,phy:92,'

In [331]:
dict_1 ={} 

In [332]:
for i in re.finditer(r'(.+?):(.+?),',row1):
    dict_1[i.groups()[0]] = i.groups()[1]

In [342]:
dict_2= {i.groups()[0]:i.groups()[1] for i in re.finditer(r'(.+?):(.+?),',row1)}

In [343]:
dict_2

{'name': 'rohan', 'maths': '75', 'phy': '89'}

In [321]:
dict_1

{'name:rohan,': 'name', 'maths:75,': 'maths', 'phy:89,': 'phy'}

# Character class

**a)** For the list `items`, filter all elements starting with `hand` and ending with `s` or `y` or `le`.

In [360]:
items = ['-handy', 'hand', 'handy', 'unhand', 'hands', 'handle']

In [361]:
re.search('\Ahand\Z','hand')

<re.Match object; span=(0, 0), match=''>

In [368]:
[w for w in items if re.search(r'\Ahand([sy]|le)',w)]

['handy', 'hands', 'handle']

In [369]:
[w for w in items if re.search(r'\Ahand.*(s|y|le)',w)]

['handy', 'hands', 'handle']

In [362]:
[w for w in items if re.fullmatch(r'hand([sy]|le)', w)]

['handy', 'hands', 'handle']

**b)** Replace all whole words `reed` or `read` or `red` with `X`

In [370]:
ip = 'redo red credible :read: rod reed'

In [385]:
re.sub(r'\b(reed|red|read)\b','X',ip)

'redo X credible :X: rod X'

In [384]:
re.sub(r'\bre[ae]?d\b',"X",ip)

'redo X credible :X: rod X'

**c)** For the list `words`, filter all elements containing `e` or `i` followed by `l` or `n`. Note that the order mentioned should be followed.


In [386]:
words = ['surrender', 'unicorn', 'newer', 'door', 'empty', 'eel', 'pest']

In [390]:
[w for w in words if re.search('[ei].*[ln]',w)]

['surrender', 'unicorn', 'eel']

**d)** For the list `words`, filter all elements containing `e` or `i` and `l` or `n` in any order.

In [391]:
words = ['surrender', 'unicorn', 'newer', 'door', 'empty', 'eel', 'pest']


In [396]:
[w for w in words if re.search(r'[ei].*[ln]|[ln].*[ei]',w)]

['surrender', 'unicorn', 'newer', 'eel']

**e)** Extract all hex character sequences, with `0x` optional prefix. Match the characters case insensitively, and the sequences shouldn't be surrounded by other word characters.

In [398]:
str1 = '128A foo 0xfe32 34 0xbar'
str2 = '0XDEADBEEF place 0x0ff1ce bad'


In [399]:
pat= re.compile(r'\b(0x)?[\da-f]+\b')

In [401]:
hex_seq = re.compile(r'\b(0x)?[\da-f]+\b', flags=re.I)

In [403]:
[w[0] for w in hex_seq.finditer(str1)]

['128A', '0xfe32', '34']

In [404]:
[w[0] for w in hex_seq.finditer(str2)]

['0XDEADBEEF', '0x0ff1ce', 'bad']

**f)** Delete from `(` to the next occurrence of `)` unless they contain parentheses characters in between.

In [405]:
str1 = 'def factorial()'
str2 = 'a/b(division) + c%d(#modulo) - (e+(j/k-3)*4)'
str3 = 'Hi there(greeting). Nice day(a(b)'

In [422]:
remove_parentheses = re.compile(r'\([^()]*\)') 

In [423]:
remove_parentheses.sub('',str1)

'def factorial'

In [420]:
remove_parentheses.sub('',str2)

'a/b + c%d - *4)'

In [424]:
remove_parentheses.sub('',str3)

'Hi there. Nice day(a'

**g)** For the list `words`, filter all elements not starting with `e` or `p` or `u`.

In [425]:
words = ['surrender', 'unicorn', 'newer', 'door', 'empty', 'eel', 'pest']

In [427]:
[i for i in words if re.search(r'^[^epu]', i)]

['surrender', 'newer', 'door']

In [428]:
[i for i in words if re.search(r'\A[^epu]', i)]

['surrender', 'newer', 'door']

**h)** For the list `words`, filter all elements not containing `u` or `w` or `ee` or `-`.

In [429]:
words = ['p-t', 'you', 'tea', 'heel', 'owe', 'new', 'reed', 'ear']


In [435]:
[i for i in words if not re.search(r'[uw-]|ee', i)]

['tea', 'ear']

**i)** The given input strings contain fields separated by `,` and fields can be empty too. Replace last three fields with `WHTSZ323`.


In [436]:
row1 = '(2),kite,12,,D,C,,'
row2 = 'hi,bye,sun,moon'

In [466]:
pat = re.compile(r'(,[^,]*){3}\Z')

In [469]:
pat.sub(',WHTSZ323',row1)

'(2),kite,12,,D,WHTSZ323'

In [470]:
pat.sub(',WHTSZ323',row2)

'hi,WHTSZ323'

**j)** Split the given strings based on consecutive sequence of digit or whitespace characters.

In [478]:
str1 = 'lion \t Ink32onion Nice'
str2 = '**1\f2\n3star\t7 77\r**'

In [479]:
pat = re.compile('[\d\s]+')


In [481]:
pat.split(str1)

['lion', 'Ink', 'onion', 'Nice']

In [482]:
pat.split(str2)

['**', 'star', '**']

**k)** Delete all occurrences of the sequence `<characters>` where `characters` is one or more non `>` characters and cannot be empty.


In [483]:
ip = 'a<apple> 1<> b<bye> 2<> c<cat>'

In [503]:
re.sub(r'<[a-z]+>','',ip)

'a 1<> b 2<> c'

In [504]:
re.sub(r'<[^>]+>','',ip)

'a 1<> b 2<> c'

In [505]:
re.sub(r'<\w+>','',ip)

'a 1<> b 2<> c'

**l)** `\b[a-z](on|no)[a-z]\b` is same as `\b[a-z][on]{2}[a-z]\b`. True or False? Sample input lines shown below might help to understand the differences, if any.

False. `[on]{2}` will also match oo and nn

In [506]:
print('known\nmood\nknow\npony\ninns')

known
mood
know
pony
inns


**m)** For the given list, filter all elements containing any number sequence greater than `624`.

In [508]:
items = ['hi0000432abcd', 'car00625', '42_624 0512', '3.14 96 2 foo1234baz']

In [509]:
[e for e in items if any(int(m[0])>624 for m in re.finditer(r'\d+', e))]

['car00625', '3.14 96 2 foo1234baz']

**n)** Count the maximum depth of nested braces for the given strings. Unbalanced or wrongly ordered braces should return `-1`. Note that this will require a mix of regular expressions and Python code.

**o)** By default, `str.split` method will split on whitespace and remove empty strings from the result. Which `re` module function would you use to replicate this functionality?


## `\t` and `\n`

In [517]:
ip = ' \t\r  so  pole\t\t\t\n\nlit in to \r\n\v\f  '

`\t` =  white space and `\n` = new line

In [518]:
ip.split()

['so', 'pole', 'lit', 'in', 'to']

In [520]:
re.findall(r'\S+', ip)

['so', 'pole', 'lit', 'in', 'to']


**p)** Convert the given input string to two different lists as shown below.

## `\W` 
## `(\W)`

In [526]:
ip = 'price_42 roast^\t\n^-ice==cat\neast'

In [528]:
re.split(r'\W+',ip)

['price_42', 'roast', 'ice', 'cat', 'east']

In [530]:
re.split(r'(\W+)',ip)

['price_42', ' ', 'roast', '^\t\n^-', 'ice', '==', 'cat', '\n', 'east']

**q)** Filter all elements whose first non-whitespace character is not a `#` character. Any element made up of only whitespace characters should be ignored as well.

In [532]:
items = ['    #comment', '\t\napple #42', '#oops', 'sure', 'no#1', '\t\r\f']

In [533]:
[e for e in items if re.search(r'\A\s*[^#\s]', e)]

['\t\napple #42', 'sure', 'no#1']

# Groupings and backreferences
IMP

**a)** Replace the space character that occurs after a word ending with `a` or `r` with a newline character.

In [534]:
ip = 'area not a _a2_ roar took 22'

In [535]:
print(re.sub(r'([ar]) ', r'\1\n', ip))

area
not a
_a2_ roar
took 22


**b)** Add `[]` around words starting with `s` and containing `e` and `t` in any order.

In [536]:
ip = 'sequoia subtle exhibit asset sets tests site'

In [543]:
re.sub(r'\bs\w*(e\w*t|t\w*e)\w*','[\g<0>]', ip)

'sequoia [subtle] exhibit asset [sets] tests [site]'

**c)** Replace all whole words with `X` that start and end with the same word character. Single character word should get replaced with `X` too, as it satisfies the stated condition.


In [544]:
ip = 'oreo not a _a2_ roar took 22'

In [556]:
re.sub(r'\b(\w|(\w)\w*\2)\b', 'X', ip)

'X not X X X took X'

**d)** Convert the given **markdown** headers to corresponding **anchor** tag. Consider the input to start with one or more `#` characters followed by space and word characters. The `name` attribute is constructed by converting the header to lowercase and replacing spaces with hyphens. Can you do it without using a capture group?

In [558]:
header1 = '# Regular Expressions'
header2 = '## Compiling regular expressions'

In [559]:
##### add your solution here for header1
# <a name="regular-expressions"></a>Regular Expressions'
##### add your solution here for header2
## <a name="compiling-regular-expressions"></a>Compiling regular expressions'

**e)** Convert the given **markdown** anchors to corresponding **hyperlinks**.

In [561]:
anchor1 = '# <a name="regular-expressions"></a>Regular Expressions'
anchor2 = '## <a name="subexpression-calls"></a>Subexpression calls'

In [564]:
hyperlink = re.compile(r'[^"]+"([^"]+)"></a>(.+)')

In [566]:
hyperlink.sub(r'[\g<1>](\g<2>)',anchor1)

'[regular-expressions](Regular Expressions)'

In [567]:
hyperlink.sub(r'[\g<1>](\g<2>)',anchor2)

'[subexpression-calls](Subexpression calls)'

## `\2`
backpreference

**f)** Count the number of whole words that have at least two occurrences of consecutive repeated alphabets. For example, words like `stillness` and `Committee` should be counted but not words like `root` or `readable` or `rotational`.

In [568]:
ip = '''oppressed abandon accommodation bloodless
carelessness committed apparition innkeeper
occasionally afforded embarrassment foolishness
depended successfully succeeded
possession cleanliness suppress'''

In [570]:
len(re.findall(r'\b(\w*(\w)\2){2}\w*\b', ip))

13

## reapating sequence

**g)** For the given input string, replace all occurrences of digit sequences with only the unique non-repeating sequence. For example, `232323` should be changed to `23` and `897897` should be changed to `897`. If there no repeats (for example `1234`) or if the repeats end prematurely (for example `12121`), it should not be changed.

In [572]:
ip = '1234 2323 453545354535 9339 11 60260260'

## \1
backpreference

In [574]:
re.sub(r'\b(\d+)\1+\b', r'\1', ip)
# (\d+) that group given reference as a 1

'1234 23 4535 9339 1 60260260'

**h)** Replace sequences made up of words separated by `:` or `.` by the first word of the sequence. Such sequences will end when `:` or `.` is not followed by a word character.


In [576]:
ip = 'wow:Good:2_two:five: hi-2 bye kite.777.water.'

In [577]:
re.sub(r'(\w+)[:.](\w+[:.])+', r'\1', ip)

'wow hi-2 bye kite'

**i)** Replace sequences made up of words separated by `:` or `.` by the last word of the sequence. Such sequences will end when `:` or `.` is not followed by a word character.


In [578]:
ip = 'wow:Good:2_two:five: hi-2 bye kite.777.water.'

In [579]:
re.sub(r'((\w+)[:.])+', r'\2', ip)

'five hi-2 bye water'

**j)** Split the given input string on one or more repeated sequence of `cat`.

In [580]:
ip = 'firecatlioncatcatcatbearcatcatparrot'


In [581]:
re.split(r'(cat)+',ip )

['fire', 'cat', 'lion', 'cat', 'bear', 'cat', 'parrot']

## `(?:<regex>)`
Creates a non-capturing group.

In [582]:
re.split(r'(?:cat)+', ip)

['fire', 'lion', 'bear', 'parrot']

**k)** For the given input string, find all occurrences of digit sequences with at least one repeating sequence. For example, `232323` and `897897`. If the repeats end prematurely, for example `12121`, it should not be matched.

```ruby

In [583]:
ip = '1234 2323 453545354535 9339 11 60260260'

In [584]:
pat = re.compile(r'\b(\d+)\1+\b')


In [585]:
[m[0] for m in pat.finditer(ip)]

['2323', '453545354535', '11']

In [586]:
pat.findall(ip)

['23', '4535', '1']

**l)** Convert the comma separated strings to corresponding `dict` objects as shown below. The keys are `name`, `maths` and `phy` for the three fields in the input strings.

In [587]:
row1 = 'rohan,75,89'
row2 = 'rose,88,92'

In [598]:
pat = re.compile("(?P<name>\w+),(?P<maths>\d{2}),(?P<phy>\d{2})")

In [599]:
pat.search(row1).groupdict()

{'name': 'rohan', 'maths': '75', 'phy': '89'}

In [600]:
pat.search(row2).groupdict()

{'name': 'rose', 'maths': '88', 'phy': '92'}

**m)** Surround all whole words with `()`. Additionally, if the whole word is `imp` or `ant`, delete them. Can you do it with single substitution?

In [601]:
ip = 'tiger imp goat eagle ant important'

In [607]:
re.sub(r'\b(?:imp|ant|(\w+))\b', r'(\1)', ip)

'(tiger) () (goat) (eagle) () (important)'

In [613]:
re.sub(r'\b(?:imp|ant|(\w+))\b',r'(\1)',ip)

'(tiger) () (goat) (eagle) () (important)'

**n)** Filter all elements that contains a sequence of lowercase alphabets followed by `-` followed by digits. They can be optionally surrounded by `{{` and `}}`. Any partial match shouldn't be part of the output.


In [614]:
ip = ['{{apple-150}}', '{{mango2-100}}', '{{cherry-200', 'grape-87']

In [615]:
[w for w in ip if re.fullmatch(r'({{)?[a-z]+-\d+(?(1)}})', w)]

['{{apple-150}}', 'grape-87']


**o)** The given input string has sequences made up of words separated by `:` or `.` and such sequences will end when `:` or `.` is not followed by a word character. For all such sequences, display only the last word followed by `-` followed by first word.

In [616]:
ip = 'wow:Good:2_two:five: hi-2 bye kite.777.water.'

<!-- [m.expand(r'\2-\1') for m in re.finditer(r'(\w+)[:.](?:(\w+)[:.])+', ip)] -->

# Lookarounds

Please use lookarounds for solving the following exercises even if you can do it without lookarounds. Unless you cannot use lookarounds for cases like variable length lookbehinds.


**a)** Replace all whole words with `X` unless it is preceded by `(` character.

In [617]:
ip = '(apple) guava berry) apple (mango) (grape'

In [618]:
re.sub(r'(?<!\()\b\w+', 'X', ip)

'(apple) X X) X (mango) (grape'

**b)** Replace all whole words with `X` unless it is followed by `)` character.

In [619]:
ip = '(apple) guava berry) apple (mango) (grape'

In [620]:
re.sub(r'\b\w+\b(?!\))', 'X', ip)

'(apple) X berry) X (mango) (X'

**c)** Replace all whole words with `X` unless it is preceded by `(` or followed by `)` characters.

In [621]:
ip = '(apple) guava berry) apple (mango) (grape'

In [622]:
re.sub(r'(?<!\()\b\w+\b(?!\))', 'X', ip)

'(apple) X berry) X (mango) (grape'

**d)** Extract all whole words that do not end with `e` or `n`.

In [623]:
ip = 'at row on urn e note dust n'

In [624]:
re.findall(r'\b\w+\b(?<![en])', ip)


['at', 'row', 'dust']

**e)** Extract all whole words that do not start with `a` or `d` or `n`.

In [625]:
ip = 'at row on urn e note dust n'

In [626]:
re.findall(r'(?![adn])\b\w+\b', ip)

['row', 'on', 'urn', 'e']

**f)** Extract all whole words only if they are followed by `:` or `,` or `-`.

In [627]:
ip = 'poke,on=-=so:ink.to/is(vast)ever-sit'

In [628]:
re.findall(r'\w+(?=[:,-])', ip)

['poke', 'so', 'ever']

**g)** Extract all whole words only if they are preceded by `=` or `/` or `-`.


In [629]:
ip = 'poke,on=-=so:ink.to/is(vast)ever-sit'

In [630]:
re.findall(r'(?<=[=/-])\w+', ip)

['so', 'is', 'sit']

**h)** Extract all whole words only if they are preceded by `=` or `:` and followed by `:` or `.`.

In [631]:
ip = 'poke,on=-=so:ink.to/is(vast)ever-sit'

In [632]:
re.findall(r'(?<=[=:])\w+(?=[:.])', ip)

['so', 'ink']

**i)** Extract all whole words only if they are preceded by `=` or `:` or `.` or `(` or `-` and not followed by `.` or `/`.

In [633]:
ip = 'poke,on=-=so:ink.to/is(vast)ever-sit'

In [634]:
re.findall(r'(?<=[=:.(-])\w+\b(?![/.])', ip)

['so', 'vast', 'sit']

**j)** Remove leading and trailing whitespaces from all the individual fields where `,` is the field separator.

In [636]:
csv1 = ' comma  ,separated ,values \t\r '
csv2 = 'good bad,nice  ice  , 42 , ,   stall   small'

In [637]:
remove_whitespace = re.compile(r'(?<![^,])\s+|\s+(?![^,])')

In [638]:
remove_whitespace.sub("",csv1)

'comma,separated,values'

In [639]:
remove_whitespace.sub("",csv2)

'good bad,nice  ice,42,,stall   small'

**k)** Filter all elements that satisfy all of these rules:

* should have at least two alphabets
* should have at least 3 digits
* should have at least one special character among `%` or `*` or `#` or `$`
* should not end with a whitespace character

In [640]:
pwds = ['hunter2', 'F2H3u%9', '*X3Yz3.14\t', 'r2_d2_42', 'A $B C1234']

In [641]:
pat = re.compile(r'(?=(.*[a-zA-Z]){2})(?=(.*\d){3})(?!.*\s\Z).*[%*#$]')

In [642]:
[p for p in pwds if pat.search(p)]

['F2H3u%9', 'A $B C1234']

**l)** For the given string, surround all whole words with `{}` except for whole words `par` and `cat` and `apple`.

In [643]:
ip = 'part; cat {super} rest_42 par scatter apple spar'

In [644]:
re.sub(r'\b(?!(?:par|cat|apple)\b)\w+\b', r'{\g<0>}', ip)

'{part}; cat {{super}} {rest_42} par {scatter} apple {spar}'

**m)** Extract integer portion of floating-point numbers for the given string. A number ending with `.` and no further digits should not be considered.

In [645]:
ip = '12 ab32.4 go 5 2. 46.42 5'

In [646]:
re.findall(r'\d+(?=\.\d+)', ip)

['32', '46']

**n)** For the given input strings, extract all overlapping two character sequences.

In [648]:
s1 = 'apple'
s2 = '1.2-3:4'

In [649]:
pat = re.compile(r'.(?=(.))')

In [650]:
[m[0]+m[1] for m in pat.finditer(s1)]


['ap', 'pp', 'pl', 'le']

In [651]:
[m[0]+m[1] for m in pat.finditer(s2)]

['1.', '.2', '2-', '-3', '3:', ':4']

**o)** The given input strings contain fields separated by `:` character. Delete `:` and the last field if there is a digit character anywhere before the last f

In [652]:
s1 = '42:cat'
s2 = 'twelve:a2b'
s3 = 'we:be:he:0:a:b:bother'

In [656]:
obj = re.compile(r'(.*\d.*):.*')

In [663]:
print(obj.search(s1))

<re.Match object; span=(0, 6), match='42:cat'>


In [664]:
print(obj.search(s2))

None


In [665]:
print(obj.search(s3))

<re.Match object; span=(0, 21), match='we:be:he:0:a:b:bother'>


**p)** Extract all whole words unless they are preceded by `:` or `<=>` or `----` or `#`.


In [666]:
ip = '::very--at<=>row|in.a_b#b2c=>lion----east'

In [667]:
re.findall(r'(?<![:#])(?<!<=>)(?<!-{4})\b\w+', ip)
['at', 'in', 'a_b', 'lion']

['at', 'in', 'a_b', 'lion']

**q)** Match strings if it contains `qty` followed by `price` but not if there is **whitespace** or the string `error` between them.

In [668]:
tr1 = '23,qty,price,42'
str2 = 'qty price,oh'
str3 = '3.14,qty,6,errors,9,price,3'
str4 = '42\nqty-6,apple-56,price-234,error'
str5 = '4,price,3.14,qty,4'

In [669]:
neg = re.compile(r'qty((?!\s|error).)*price')

In [670]:
bool(neg.search(str1))

False

In [671]:
bool(neg.search(str2))

False

In [672]:
bool(neg.search(str3))

False

In [673]:
bool(neg.search(str4))

True

In [674]:
bool(neg.search(str5))

False

**r)** Can you reason out why the output shown is different for these two regular expressions?

In [675]:
ip = 'I have 12, he has 2!'

In [676]:
re.sub(r'\b..\b', '{\g<0>}', ip)

'{I }have {12}{, }{he} has{ 2}!'

In [677]:
re.sub(r'(?<!\w)..(?!\w)', '{\g<0>}', ip)

'I have {12}, {he} has {2!}'

# Flags

**a)** Remove from first occurrence of `hat` to last occurrence of `it` for the given input strings. Match these markers case insensitively.

In [679]:
s1 = 'But Cool THAT\nsee What okay\nwow quite'
s2 = 'it this hat is sliced HIT.'

In [680]:
pat = re.compile(r'hat.*it', flags=re.S|re.I)

In [681]:
pat.sub('', s1)

'But Cool Te'

In [682]:
pat.sub('', s2)


'it this .'

**b)** Delete from `start` if it is at the beginning of a line up to the next occurrence of the `end` at the end of a line. Match these markers case insensitively.

In [683]:
para = '''\
good start
start working on that
project you always wanted
to, do not let it end
hi there
start and end the end
42
Start and try to
finish the End
bye'''

In [684]:
pat = re.compile(r'(?ims)^start.*?end$')

In [685]:
print(pat.sub('', para))

good start

hi there

42

bye


**c)** For the given input strings, match all of these three patterns:

In [686]:
s1 = 'This is nice and Cool'
s2 = 'Nice and cool this is'
s3 = 'What is so nice and cool about This?'

In [687]:
pat = re.compile(r'(?i)(?=.*nice)(?=.*cool)(?-i:.*This)')

In [688]:
bool(pat.search(s1))

True

In [689]:
bool(pat.search(s2))

False

In [690]:
bool(pat.search(s3))

True

**d)** For the given input strings, match if the string begins with `Th` and also contains a line that starts with `There`.

In [691]:
s1 = 'There there\nHave a cookie'
s2 = 'This is a mess\nYeah?\nThereeeee'
s3 = 'Oh\nThere goes the fun'

In [692]:
pat = re.compile(r'\A(?=Th)(?ms:.*^There)')

In [693]:
bool(pat.search(s1))

True

In [694]:
bool(pat.search(s2))

True

In [695]:
bool(pat.search(s3))

False

**e)** Explore what the `re.DEBUG` flag does. Here's some example patterns to check out.

* `re.compile(r'\Aden|ly\Z', flags=re.DEBUG)`
* `re.compile(r'\b(0x)?[\da-f]+\b', flags=re.DEBUG)`
* `re.compile(r'\b(?:0x)?[\da-f]+\b', flags=re.I|re.DEBUG)`

# Unicode

**a)** Output `True` or `False` depending on input string made up of ASCII characters or not. Consider the input to be non-empty strings and any character that isn't part of 7-bit ASCII set should give `False`. Do you need regular expressions for this?

In [697]:
str1 = '123—456'
str2 = 'good fοοd'
str3 = 'happy learning!'
str4 = 'İıſK'

In [698]:
str1.isascii()

False

In [699]:
str2.isascii()

False

In [700]:
str3.isascii()

True

In [701]:
str4.isascii()

False

**b)** Does `.` quantifier with `re.ASCII` flag enabled match non-ASCII characters?

**c)** Explore the following Q&A threads.

* [stackoverflow: remove powered number from string](https://stackoverflow.com/questions/57553721/remove-powered-number-from-string-in-python)
* [stackoverflow: regular expression for French characters](https://stackoverflow.com/questions/1922097/regular-expression-for-french-characters)

# regex module

**a)** Filter all elements whose first non-whitespace character is not a `#` character. Any element made up of only whitespace characters should be ignored as well.


In [710]:
import regex

In [711]:
items = ['    #comment', '\t\napple #42', '#oops', 'sure', 'no#1', '\t\r\f']

In [712]:
[e for e in items if regex.search(r'\A\s*+[^#]', e)]

['\t\napple #42', 'sure', 'no#1']

**b)** Replace sequences made up of words separated by `:` or `.` by the first word of the sequence and the separator. Such sequences will end when `:` or `.` is not followed by a word character.

In [724]:
ip = 'wow:Good:2_two:five: hi bye kite.777.water.'

In [725]:
regex.sub(r'(\w+[:.])(?1)+', r'\1', ip)

'wow: hi bye kite.'

**c)** The given list of strings has fields separated by `:` character. Delete `:` and the last field if there is a digit character anywhere before the last field.

In [726]:
items = ['42:cat', 'twelve:a2b', 'we:be:he:0:a:b:bother']

In [727]:
[regex.sub(r'\d.*\K:.*', '', e) for e in items]

['42', 'twelve:a2b', 'we:be:he:0:a:b']

**d)** Extract all whole words unless they are preceded by `:` or `<=>` or `----` or `#`.


In [728]:
ip = '::very--at<=>row|in.a_b#b2c=>lion----east'

In [729]:
regex.findall(r'(?<![:#]|<=>|-{4})\b\w+', ip)


['at', 'in', 'a_b', 'lion']

**e)** The given input string has fields separated by `:` character. Extract all fields if the previous field contains a digit character.


In [730]:
ip = 'vast:a2b2:ride:in:awe:b2b:3list:end'

In [731]:
regex.findall(r'(?<=\d[^:]*:)[^:]+', ip)

['ride', '3list', 'end']

**f)** The given input string has fields separated by `:` character. Delete all fields, including the separator, unless the field contains a digit character. Stop deleting once a field with digit character is found.

In [732]:
row1 = 'vast:a2b2:ride:in:awe:b2b:3list:end'
row2 = 'um:no:low:3e:s4w:seer'

In [733]:
pat = regex.compile(r'\G[^\d:]+:')

In [734]:
pat.sub('', row1)

'a2b2:ride:in:awe:b2b:3list:end'

In [735]:
pat.sub('', row2)

'3e:s4w:seer'

**g)** For the given input strings, extract `if` followed by any number of nested parentheses. Assume that there will be only one such pattern per input string.

In [740]:
ip1 = 'for (((i*3)+2)/6) if(3-(k*3+4)/12-(r+2/3)) while()'
ip2 = 'if+while if(a(b)c(d(e(f)1)2)3) for(i=1)'

In [741]:
pat=regex.compile(r'if(\((?:[^()]++|(?1))++\))')

In [742]:
pat.search(ip1)[0]

'if(3-(k*3+4)/12-(r+2/3))'

In [743]:
pat.search(ip2)[0]

'if(a(b)c(d(e(f)1)2)3)'

**h)** Read about `POSIX` flag from https://pypi.org/project/regex/. Is the following code snippet showing the correct output?

In [744]:
words = 'plink incoming tint winter in caution sentient'

In [745]:
change = regex.compile(r'int|in|ion|ing|inco|inter|ink', flags=regex.POSIX)


In [747]:
change.sub('X', words)

'plX XmX tX wX X cautX sentient'

**i)** Extract all whole words for the given input strings. However, based on user input `ignore`, do not match words if they contain any character present in the `ignore` variable.

In [756]:
s1 = 'match after the last newline character'
s2 = 'and then you want to test'

**j)** Retain only punctuation characters for the given strings (generated from codepoints). Use Unicode character set definition for punctuation for solving this exercise.

In [719]:
s1 = ''.join(chr(c) for c in range(0, 0x80))
s2 = ''.join(chr(c) for c in range(0x80, 0x100))
s3 = ''.join(chr(c) for c in range(0x2600, 0x27ec))

In [ ]:
pat = regex.compile(r'\P{P}+')

**k)** For the given **markdown** file, replace all occurrences of the string `python` (irrespective of case) with the string `Python`. However, any match within code blocks that start with whole line ` ```python ` and end with whole line ` ``` ` shouldn't be replaced. Consider the input file to be small enough to fit memory requirements.

Refer to [github: exercises folder](https://github.com/learnbyexample/py_regular_expressions/tree/master/exercises) for files `sample.md` and `expected.md` required to solve this exercise.

In [ ]:
ip_str = open('sample.md', 'r').read()

**l)** For the given input strings, construct a word that is made up of last characters of all the words in the input. Use last character of last word as first character, last character of last but one word as second character and so on.

In [721]:
s1 = 'knack tic pi roar what'
s2 = '42;rod;t2t2;car'

In [722]:
regex.split(r'(\d+)(?!.*\d)', s1)

['knack tic pi roar what']

In [723]:
regex.split(r'(\d+)(?!.*\d)', s2)

['42;rod;t2t', '2', ';car']

**m)** Replicate `str.rpartition` functionality with regular expressions. Split into three parts based on last match of sequences of digits, which is `777` and `12` for the given input strings.

In [720]:
s1 = 'Sample123string42with777numbers'
s2 = '12apples'

**n)** Read about fuzzy matching on https://pypi.org/project/regex/. For the given input strings, return `True` if they are exactly same as `cat` or there is exactly one character difference. Ignore case when comparing differences. For example, `Ca2` should give `True`. `act` will be `False` even though the characters are same because position should be maintained.

In [ ]:
pat = regex.compile(r'(?i)(cat){s<=1}')
